#!/bin/bash
find -type f -name "*.gif" | rev | cut -d "/" -f 1 | rev | cut -d "." -f 1 | tr '[:upper:]' '[:lower:]' | LC_ALL=C sort -f #find -type f -name ".gif" | rev | cut -d "/" -f 1 | cut -d . -f 2- | rev | LC_ALL=C sort -f
